# Generated by Django 3.2.5 on 2021-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome Completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('formacao', models.CharField(choices=[('Ens.Médio', 'Ens.Médio'), ('Superior Incopleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo')], max_length=50, verbose_name='Formação')),
            ],
            options={
                'verbose_name': 'Curriculo',
                'verbose_name_plural': 'Curriculos',
            },
        ),
    ]
